global using System.Data;
global using System.IO.Abstractions;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Immutable;
global using System.ComponentModel;
global using System.Diagnostics;
global using Humanizer;
global using JetBrains.Annotations;
global using Spectre.Console;
global using Spectre.Console.Cli;
global using static Soddi.Logger;
